// Curated follow-along routines, 5–16 min. [id, title, channel, length]
// Add or remove lines freely; the app picks from whichever list matches the time of day.
window.VIDEOS = {
  morning: [
    ["cacwri2wio4", "5 Minute Morning Mobility Routine", "Tom Merrick", "6:51"],
    ["krXeVORBVLE", "5 Stretches I Do Everyday", "Tom Merrick", "7:25"],
    ["XIXjdireZzE", "Morning Flexibility Routine", "Tom Merrick × Vivobarefoot", "9:04"],
    ["AM_lVBx1f6Q", "10 Minute Morning Mobility — Wake Up & Move", "EDR Fitness", "10:19"],
    ["o45n57HGzGw", "10 Minute Morning Mobility — Feel Brand New", "EDR Fitness", "10:51"],
    ["aRVFt79LqCM", "10 Min. Morning Mobility Routine", "mobility by julia reppel", "10:56"],
    ["bR0djYf0hkg", "10 Min. Morning Mobility Flow", "mobility by julia reppel", "10:40"],
    ["4Bvjol_deks", "10 Min. Morning Mobility — Connect to Your Body", "mobility by julia reppel", "11:03"],
    ["Igzmhbghcd4", "10 Min Perfect Mobility Routine", "Fraser Wilson", "10:27"],
    ["P91Vegj3Qxg", "10 Min Mobility Routine for Recovery", "Fraser Wilson", "10:24"],
    ["t2jel6q1GRk", "Quick Morning Stretching Routine", "Tone and Tighten", "9:11"],
    ["COO2S7lPBzA", "10 Minute Total Body Stretch", "Tone and Tighten", "10:49"],
    ["WRwVbvkcSZk", "10 Min Full Body Morning Mobility", "Yoga With Tim", "11:21"],
    ["bQa6VKPoyFw", "10 Min Morning Yoga Stretch & Mobility", "Yoga With Tim", "11:19"],
    ["3R_BSL7nOOM", "Full Body Stretching with Strength", "Strength Side", "10:50"],
    ["4pfCBO3BGvg", "10 Min. Daily Mobility Routine", "Mady Morrison", "10:54"],
    ["sAf67xFS-qE", "5 Min. Morning Stretch", "Mady Morrison", "5:58"],
    ["qOxcAvHpnEQ", "10 Minute Mobility Routine Every Day", "JTM_FIT", "11:05"],
    ["Ptj-NEb5oB4", "5 Minute Morning Stretches", "Jessica Valant", "6:31"],
    ["Ef6LwAaB3_E", "5 Min Daily Stretch", "MadFit", "6:47"],
    ["K_d_ojyolY8", "5 Minute Morning Stretch & Mobility", "Body Fix Exercises", "6:20"],
    ["Kvoq4luIYVc", "5 Minute Full Body Stretch", "Yoga With Adriene", "6:40"],
    ["9wl-O_H9q5M", "5 min. Daily Full Body Stretch", "Kaleigh Cohen Strength", "6:09"],
    ["Bpsoqk8v_bE", "5 Minute Daily Mobility Workout", "Lucy Wyndham-Read", "5:17"],
    // 12–16 min
    ["vYEeGGbsp_s", "Do This Every Morning: 15 Minute Mobility", "EDR Fitness", "15:36"],
    ["5abdqQztF7M", "15 Minute Morning Flexibility Routine", "Tom Merrick", "16:01"],
    ["R3WDe7byUXo", "15 Minute Full Body Mobility Routine", "Tom Merrick", "14:53"],
    ["L_xrDAtykMI", "15 Minute Beginner Stretch Flexibility Routine", "Tom Merrick", "15:00"],
    ["0VrLgzwTmTg", "10 Minute Morning Mobility Routine", "Tom Merrick", "12:23"],
    ["yDOImN60yhQ", "15 Min. Morning Mobility Routine", "mobility by julia reppel", "15:54"],
    ["ddlULhzLbPU", "15 Min. Daily Mobility Routine", "mobility by julia reppel", "15:50"],
    ["4yj_DJPedIc", "15 Min Morning Mobility Routine", "Fraser Wilson", "15:25"],
    ["TFSYNWPYujQ", "15 Minute Full Body Mobility for Athletes", "Soheil Var", "15:19"],
    ["0oYnT5OBzKg", "15 Minute Morning Mobility for Full Body Flexibility", "Yoga With Tim", "15:25"],
    ["E2SOrScNbww", "Full Body Stretching Routine (15 min.)", "Strength Side", "15:57"],
    ["1DZmk2dobvU", "Daily Mobility Reset", "Tom Morrison", "13:00"],
    ["oMR5UOikE3k", "10 Minute Full Body Mobility Flow", "Tom Morrison", "12:08"],
    ["yDXBRssBpVo", "10 Minute Mobility & Stretching Routine", "Citizen Athletics", "13:33"],
  ],
  evening: [
    ["_9JZuOO9E_w", "10 Minute Evening Stretch — Better Sleep", "Mady Morrison", "10:19"],
    ["p3EJuBxEjt0", "8 Minute Evening Yoga — Wind Down", "Yoga with Kassandra", "8:47"],
    ["ChHxbJuUR9Q", "10 min Evening Yoga Stretch", "Yoga with Kassandra", "11:08"],
    ["q-76wcHi9GM", "Bedtime Yoga Stretch for Good Sleep", "Yoga with Kassandra", "11:03"],
    ["OS6MhBfs800", "10 Minute Bedtime Stretches", "Jessica Valant", "10:07"],
    ["TKObxC2t2vc", "10 min Bedtime Yoga Stretch", "Yoga with Uliana", "10:50"],
    ["8S4WOgXyQMo", "10 minute Bedtime Yoga for Stress", "SarahBethYoga", "10:12"],
    ["GuhwzjKK1os", "10 minute Relaxing Bedtime Yoga Stretch", "SarahBethYoga", "11:52"],
    ["9aFl_KvK5tc", "10 Min Evening Stretch — Melt Away Tension", "Yoga With Nancy", "10:06"],
    ["rxkOM2YjHPc", "8 Min Bedtime Stretch", "Yoga With Nancy", "8:46"],
    ["4XX6AHSYgHA", "Nighttime Stretching Routine", "Tone and Tighten", "9:10"],
    ["wBQSErShw0c", "10 Min Bedtime Pilates", "Hong Rabbit", "10:39"],
    ["F0CGLGSdKGA", "5 Min. Evening Mobility Routine", "mobility by julia reppel", "5:29"],
    ["s_jYERBRq8A", "5 Min. Quick Evening Stretch", "mobility by julia reppel", "6:48"],
    ["I4Zgq6_XfaQ", "10 Min. Gentle Evening Stretch", "mobility by julia reppel", "11:51"],
    ["8O8OR68dMIk", "10 Minute Bedtime Mobility", "EDR Fitness", "10:29"],
    ["fDNtf4t_sfg", "Bedtime Mobility Routine", "WorkoutsbyDavid", "9:33"],
    ["DTPooiWWlos", "5 Minute Before Bed Stretching", "Darwin Jose", "7:45"],
    ["SqFniT-Oyt8", "5 Minute Yoga for Sleep", "Yoga With Bird", "6:14"],
    ["N80XRg_NWSI", "5 Minute Evening Stretch", "Body Fix Exercises", "6:00"],
    ["CqUs9NFPgoE", "Before Bed When Your Mind Is Still Awake", "Breathe and Flow", "5:38"],
    // 12–16 min
    ["mjf7Fkmuxhc", "Relaxing Evening Flexibility Routine", "Tom Merrick", "14:04"],
    ["1u30bEkE2dE", "15 Minute Relaxed Stretching Routine", "Tom Merrick", "15:59"],
    ["u_eBTabTA0M", "Evening Flexibility Routine", "Tom Merrick × Vivobarefoot", "12:36"],
    ["3u9z9lg9_4k", "15 Min. Bedtime Mobility", "mobility by julia reppel", "16:01"],
    ["CLDHeV9OI5U", "10-Minute Bedtime Yoga", "Yoga With Adriene", "13:27"],
    ["ZPwP7zjocZU", "10 min Evening Full Body Yoga Stretch", "Yoga with Kassandra", "13:30"],
    ["5Kfv13sGbZQ", "10 Minute Evening Yoga for Better Sleep", "Yoga With Bird", "12:43"],
    ["RI5gOBeTqyE", "Do This Before Bed When Your Body Won't Let Go", "Breathe and Flow", "14:08"],
    ["MQs4xGn7EOk", "Evening Stretches before Bed", "Journey to Mobility", "14:51"],
    ["9huvrKzF2ss", "15 Min Evening Stretch for Better Sleep", "Yoga With Nancy", "15:26"],
    ["y0fms_yJwR0", "10 Min Evening Yoga Stretch — Sleep Deep", "Travis Eliot", "12:51"],
  ],
};
